# Generated by Django 5.0 on 2023-12-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Pekerja Magang', 'Pekerja Magang'), ('Staff Junior', 'Staff Junior'), ('Staff Senior', 'Staff Senior'), ('Team Leader', 'Team Leader'), ('Spesialis Departemen', 'Spesialis Departemen'), ('Kepala Departemen', 'Kepala Departemen'), ('Asisten Eksekutif', 'Asisten Eksekutif'), ('Anggota Dewan', 'Anggota Dewan'), ('Eksekutif C-Suite', 'Eksekutif C-Suite'), ('Wakil Presiden', 'Wakil Presiden'), ('Presiden', 'Presiden'), ('Chief Executive Officer (CEO)', 'Chief Executive Officer (CEO)')], max_length=50),
        ),
    ]
